'use client';

import { useMenuStore, useFilteredMenuItems } from '@/store/menu-store';
import { DishCard } from './dish-card';

export function FancyMenu() {
  const menuItems = useFilteredMenuItems();
  const parsedMenu = useMenuStore((state) => state.parsedMenu);

  if (menuItems.length === 0) {
    return null;
  }

  // Group items by category
  const categorizedItems = menuItems.reduce(
    (acc, item) => {
      const category = item.category || 'Specialties';
      if (!acc[category]) acc[category] = [];
      acc[category].push(item);
      return acc;
    },
    {} as Record<string, typeof menuItems>
  );

  return (
    <div className="bg-gradient-to-br from-amber-50 to-orange-50 p-6 md:p-10 rounded-2xl border border-amber-200 shadow-lg">
      {/* Decorative header */}
      <div className="text-center mb-10 pb-6 border-b-2 border-amber-300">
        <div className="text-amber-600 text-sm uppercase tracking-widest mb-2">Visual Menu</div>
        <h2 className="font-serif text-4xl text-amber-900">Menu</h2>
        {parsedMenu?.originalLanguage && parsedMenu.originalLanguage.toLowerCase() !== 'english' && (
          <p className="text-sm text-amber-700 mt-3 italic">
            Translated from {parsedMenu.originalLanguage}
          </p>
        )}
      </div>

      {/* Categories */}
      <div className="space-y-10">
        {Object.entries(categorizedItems).map(([category, items]) => (
          <div key={category}>
            <h3 className="font-serif text-2xl text-amber-800 mb-6 text-center">
              <span className="relative inline-block">
                {category}
                <span className="absolute -bottom-2 left-0 right-0 h-0.5 bg-amber-300" />
              </span>
            </h3>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              {items.map((item) => (
                <DishCard key={item.id} item={item} />
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Footer decoration */}
      <div className="mt-10 pt-6 border-t border-amber-200 text-center">
        <p className="text-xs text-amber-600">
          Images generated by AI · Actual dishes may vary
        </p>
      </div>
    </div>
  );
}
