'use client';

import { useMenuStore, useFilteredMenuItems } from '@/store/menu-store';
import { DishCard } from './dish-card';

export function FancyMenu() {
  const menuItems = useFilteredMenuItems();
  const parsedMenu = useMenuStore((state) => state.parsedMenu);

  if (menuItems.length === 0) {
    return null;
  }

  // Group items by category
  const categorizedItems = menuItems.reduce(
    (acc, item) => {
      const category = item.category || 'Specialties';
      if (!acc[category]) acc[category] = [];
      acc[category].push(item);
      return acc;
    },
    {} as Record<string, typeof menuItems>
  );

  return (
    <div className="bg-white p-6 md:p-10 rounded-xl border border-slate-200 shadow-sm">
      {/* Header */}
      <div className="text-center mb-10 pb-6 border-b border-slate-200">
        <div className="text-indigo-500 text-xs font-medium uppercase tracking-widest mb-2">Visual Menu</div>
        <h2 className="font-serif text-3xl text-slate-900">Menu</h2>
        {parsedMenu?.originalLanguage && parsedMenu.originalLanguage.toLowerCase() !== 'english' && (
          <p className="text-sm text-slate-500 mt-3 italic">
            Translated from {parsedMenu.originalLanguage}
          </p>
        )}
      </div>

      {/* Categories */}
      <div className="space-y-10">
        {Object.entries(categorizedItems).map(([category, items]) => (
          <div key={category}>
            <h3 className="text-xl font-semibold text-slate-800 mb-6 text-center">
              <span className="relative inline-block">
                {category}
                <span className="absolute -bottom-1.5 left-0 right-0 h-0.5 bg-indigo-300 rounded-full" />
              </span>
            </h3>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              {items.map((item) => (
                <DishCard key={item.id} item={item} itemIndex={menuItems.indexOf(item)} />
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-10 pt-6 border-t border-slate-200 text-center">
        <p className="text-xs text-slate-400">
          Images generated by AI. Actual dishes may vary.
        </p>
      </div>
    </div>
  );
}
